- name: start kubernetes and install all dependencies
  hosts: all
  pre_tasks:
    - name: Install openshift client for k8s tasks
      command: python3 -m pip install --user openshift
  roles:
    - role: clear-firewall
    - role: ensure-docker
    - role: ensure-kubernetes
      vars:
        minikube_dns_resolvers:
          - '1.1.1.1'
          - '8.8.8.8'
    - role: use-buildset-registry
      buildset_registry_docker_user: root
  post_tasks:
    - name: check kubernetes connection
      command: timeout 10s kubectl get pods
      register: _api_ready
      until: _api_ready.rc == 0
      retries: 6
      delay: 10

    - name: Setup cert-manager
      command: "kubectl {{ item }}"
      when:
        - withCertManager
      loop:
        - create namespace cert-manager
        - apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.14.0/cert-manager.yaml
